FROM debian:10

RUN apt update\
  && apt install -y python3 python3-pip default-libmysqlclient-dev\
  && rm -rf /var/lib/apt/lists/*\
  && pip3 install -U pip gunicorn

RUN mkdir -p /app/code && mkdir -p /app/bind

WORKDIR /app/code
COPY . /app/code

CMD ./entrypoint.sh
