version: '2.3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    depends_on:
      - mysql
    environment:
      WSGI_NAME: pigpen
      PROD: 1
      DOCKER: 1
      WORKERS: 3
    volumes:
      - media:/app/media
      - static:/app/static
      - bind:/app/bind
      - secret:/app/secret

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - django
    volumes:
      - media:/app/media
      - static:/app/static
      - bind:/app/bind

  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - sql:/var/lib/mysql

volumes:
  sql:
  media:
  static:
  secret:
  bind:

