# Generated by Django 2.2.3 on 2019-07-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0004_auto_20190716_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('stu', 'Student'), ('mtr', 'Adult'), ('asib', 'Sibling')], default='stu',
                                   max_length=10),
        ),
    ]
