# Generated by Django 2.2.3 on 2019-07-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0006_auto_20190718_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
