# Generated by Django 2.2.3 on 2019-07-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0007_member_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='length',
            field=models.IntegerField(default=4),
        ),
    ]
