# Generated by Django 2.2.3 on 2019-07-22 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0008_meeting_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.CharField(
                    choices=[('stoff', 'Student Officers'), ('abod', 'Adult Board of Directors'),
                             ('stsub', 'Student Subsystem/Subteam Leads'), ('adsub', 'Adult Subsystem/Subteam Leads'),
                             ('stbus', 'Student Business Leads'), ('adbus', 'Adult Business Leads')], max_length=10)),
                ('sort', models.IntegerField(default=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teammanager.Member')),
            ],
        ),
    ]
