# Generated by Django 2.2.3 on 2019-07-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0010_auto_20190722_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slack',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
