# Generated by Django 2.2.3 on 2019-07-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0011_member_slack'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slack_avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='slack_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
