# Generated by Django 2.2.3 on 2019-07-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0014_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='signup_active',
        ),
    ]
