# Generated by Django 2.2.3 on 2019-07-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0015_remove_meeting_signup_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='signup_notes_needed',
            field=models.BooleanField(default=False),
        ),
    ]
