# Generated by Django 2.2.3 on 2019-08-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0016_meeting_signup_notes_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('stu', 'Student'), ('mtr', 'Adult'), ('asib', 'Sibling'), ('ext', 'Extended')], default='stu', max_length=10),
        ),
    ]
