# Generated by Django 2.2.3 on 2019-08-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0017_auto_20190805_1824'),
        ('teammanager', '0017_auto_20190805_0029'),
    ]

    operations = [
    ]
