# Generated by Django 2.2.4 on 2019-08-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0019_auto_20190805_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='outreach_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(
                choices=[('build', 'Build Meeting'), ('out', 'Outreach'), ('comp', 'Competition'), ('fun', 'Fun Event'),
                         ('othr', 'Other Non-Mandatory')], default='build', max_length=10),
        ),
    ]
