# Generated by Django 2.2.4 on 2019-08-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0020_auto_20190806_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
