# Generated by Django 2.2.4 on 2019-08-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0021_meeting_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='signup_active',
            field=models.BooleanField(default=False),
        ),
    ]
