# Generated by Django 2.2.3 on 2019-08-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0022_meeting_signup_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
