# Generated by Django 2.2.3 on 2019-08-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0023_meeting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(blank=True, to='teammanager.Member'),
        ),
    ]
