# Generated by Django 2.2.4 on 2019-08-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0026_auto_20190808_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeambuildingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('option_one', models.CharField(max_length=100)),
                ('option_two', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeambuildingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_one_selected', models.BooleanField(default=False)),
                ('option_two_selected', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teammanager.Member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teammanager.TeambuildingQuestion')),
            ],
        ),
    ]
