# Generated by Django 2.2.3 on 2019-09-01 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0027_teambuildingquestion_teambuildingresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teambuildingresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_set',
                                    to='teammanager.TeambuildingQuestion'),
        ),
    ]
