# Generated by Django 2.2.3 on 2019-09-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0028_auto_20190901_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='exchanged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
