# Generated by Django 2.2.6 on 2019-10-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0030_punch_volunteer_hrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='length',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='member',
            name='attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='outreach_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='punch',
            name='volunteer_hrs',
            field=models.FloatField(default=0),
        ),
    ]
