# Generated by Django 2.2.9 on 2020-01-01 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('teammanager', '0032_auto_20200101_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first', 'last']},
        ),
    ]
