# Generated by Django 2.2.12 on 2021-06-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0033_auto_20200101_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
