# Generated by Django 2.2.12 on 2021-06-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0034_member_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
